/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sailstats;

public class App {
    public static final boolean IS_DEBUG_MODE = true;
    public void startUp() {
        SailStatsManager sailStatsManager = new SailStatsManager(true);
    }

    public static void main(String[] args) {
        new App().startUp();
    }
}
